version: "3.9"
services:
  mongo:
    image: mongo:3.6.13
    ports:
      - "27017:27017"
  cassandra:
    image: cassandra:3.11.5
    ports:
      - 9042:9042
      - 9160:9160
      - 7199:7199
      - 8778:8778
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=test
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    command: >
      /usr/local/bin/etcd
      -name etcd0
      -advertise-client-urls http://localhost:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://0.0.0.0:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd0=http://0.0.0.0:2380
      -initial-cluster-state new
    ports:
      - "2379:2379"
